config/routes.rb
Rails.application.routes.draw do

  mount ActionCable.server => '/cable'
  devise_for :users

  resources :posts do
    member do
      get :likes
      post :comment
    end
  end

  resources :users do
    member do
      get :follow
    end
  end

  resources :notifications, only: [ :index ]
  root 'posts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/attachment.rb
class Attachment < ApplicationRecord
  belongs_to :attacheble, polymorphic: true
  has_one_attached :file 
end

app/models/comment.rb
class Comment < ApplicationRecord
  include Notificable
  belongs_to :commentable, polymorphic: true
  belongs_to :user

  def user_ids
    if self.user_id == self.commentable.user_id
      self.commentable.user_ids
    else
      self.commentable.user.following_users.pluck("followee_id").uniq
    end
  end
end

app/models/concerns/attachable.rb
module Attachable
  extend ActiveSupport::Concern

  included do
    has_one :attachment, as: :attacheble  
    accepts_nested_attributes_for :attachment
  end
end

app/models/concerns/commentable.rb
module Commentable
  extend ActiveSupport::Concern

  included do
    has_many :comments, as: :commentable  
  end
end

app/models/concerns/likeable.rb
module Likeable
  extend ActiveSupport::Concern

  included do
    has_many :likes, as: :likeable, dependent: :destroy
  end
end

app/models/follow.rb
class Follow < ApplicationRecord
	include Notificable
	
	belongs_to :follower, class_name: 'User'
  belongs_to :followee, class_name: 'User'

  validates :follower_id, uniqueness: { scope: :followee_id }
  validates :followee_id, uniqueness: { scope: :follower_id }
end

app/models/like.rb
class Like < ApplicationRecord
  include Notificable
  belongs_to :likeable, polymorphic: true, counter_cache: true
  belongs_to :user

  def user_ids
    self.likeable.user.following_users.pluck("followee_id").uniq
  end
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :item, polymorphic: true
  belongs_to :user

  scope :unviewed, ->{ where(viewed: false) }
  scope :latest, ->{ order("created_at DESC") }

  default_scope { latest }

  after_create_commit do 
    broadcast_prepend_to "broadcast_to_user_#{self.user_id}", 
      target: :notifications
  end

  after_update_commit do 
    broadcast_replace_to "broadcast_to_user_#{self.user_id}", 
      target: self
  end

  after_destroy_commit do 
    broadcast_remove_to "broadcast_to_user_#{self.user_id}", 
      target: :notifications
  end

  after_commit do
    broadcast_replace_to "broadcast_to_user_#{self.user_id}", 
      target: "notifications_count", 
      partial: "notifications/count", 
      locals: { count: self.user.unviewed_notifications_count }
  end
end

app/models/post.rb
class Post < ApplicationRecord
  include Attachable, Commentable, Notificable, Likeable

  belongs_to :user

  validates :body, presence: true
  validates :attachment, presence: true

  scope :for_followers_and_user, ->(user) { where("posts.user_id IN (#{user.followed_users.select("followee_id").to_sql}) OR posts.user_id = #{user.id}") }
  scope :user_likes, ->(user) {
    where("likes.user_id = ?", user.id).
      select("posts.id as post_id, COUNT(likes.id) as current_user_like").
        group("posts.id").count
  }


  def user_ids
    user.following_users.pluck("follower_id").uniq
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts
  has_many :notifications

  # follow users 
  has_many :followed_users, foreign_key: :follower_id, class_name: 'Follow'
  has_many :followees, through: :followed_users
  has_many :following_users, foreign_key: :followee_id, class_name: 'Follow'
  has_many :followers, through: :following_users

  scope :all_except, ->(user) { where.not(id: user) }

  def unviewed_notifications_count
    self.notifications.unviewed.count
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :authenticate_user!
	layout "feeds"
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController

  def index
    @notifications = current_user.notifications.
    									includes(item: [:user, :likeable]).
    										order(created_at: :desc)
    @notifications.update_all(viewed: true)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ likes show edit update destroy comment ]

  # GET /posts or /posts.json
  def index
    @posts = Post.for_followers_and_user(current_user).includes(:user, {comments: :user, attachment: {file_attachment: :blob}}).
              order(created_at: :desc)
    @current_user_likes = @posts.eager_load(:likes).user_likes(current_user)

  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
    @post.build_attachment
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)
    respond_to do |format|
      if @post.save
        format.html { redirect_to posts_url, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html do
          @post.build_attachment
          render :new, status: :unprocessable_entity

        end
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to posts_url, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def likes
    like = @post.likes.find_by_user_id(current_user.id)
    if like
      like.destroy!
      respond_to do |format|
        format.json { render json: { liked: false, total_likes: @post.likes.count } }
      end
    else
      @post.likes.build(user_id: current_user.id).save
      respond_to do |format|
        format.json { render json: { liked: true, total_likes: @post.likes.count} }
      end
    end 
  end

  def comment
    @post.comments.build(comment_params).save
    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Comment has been created" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params[:post][:user_id] = current_user.id
      params.require(:post).permit(:title, :body, :user_id, attachment_attributes: [:file])
    end

    def comment_params
      params[:comment][:user_id] = current_user.id
      params.require(:comment).permit(:user_id, :content)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
		@users = User.all_except(current_user)
		@followed_users = current_user.followed_users.
												where("followee_id IN (#{@users.select("id").to_sql})").
													pluck(:followee_id)
	end

	def follow
		followed = current_user.followed_users.find_by_followee_id(params[:id])
    if followed
      followed.destroy!
      respond_to do |format|
        format.json { render json: { followed: false } }
      end
    else
      current_user.followed_users.build(followee_id: params[:id]).save!
      respond_to do |format|
        format.json { render json: { followed: true } }
      end
    end 
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/heroicon_helper.rb
# frozen_string_literal: true

module HeroiconHelper
  include Heroicon::Engine.helpers
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
	
end

app/helpers/users_helper.rb
module UsersHelper
	def follow_user? id
		@followed_users.include?(id) ? 'Unfollow' : 'Follow'
	end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Instaclone</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body class="dashboard">
    <div class="container">
  <div class="row">
    <%= yield %>
    
  </div>
</div>
  </body>
</html>

app/views/layouts/feeds.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Instaclone</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload"%>
  </head>
  <body>
  		<% if user_signed_in? %>
			  <%= turbo_stream_from dom_id(current_user, :broadcast_to) %>
      	<%= render partial: 'layouts/feeds/header' %>
    	<% end %>	
    	<div class="container">
				 <div class="row">
		      <%= yield %>
		    </div>
		  </div>
  </body>
</html>

app/views/layouts/feeds/_header.html.erb
<!-- Page content wrapper-->
<div id="page-content-wrapper">
  <!-- Top navigation-->
  <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <div class="container-fluid">
    	<%= link_to posts_path, class: "nav-link" do %>
			  <span class="sr-only">InstaClone</span>
			<% end %>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ms-auto mt-2 mt-lg-0">

					<li class="nav-item">
					  <%= link_to posts_path, class: "nav-link" do %>
						  <span class="sr-only">Posts</span>
						<% end %>
          </li>
				
					<li class="nav-item">
					  <%= link_to users_path, class: "nav-link" do %>
						  <span class="sr-only">Users</span>
						<% end %>
          </li>

          <li class="nav-item active">
					  <%= link_to notifications_path, class: "nav-link notification " do %>
					  	<div class="d-flex">
							  <%= heroicon "bell", variant: :outline, options: { class: "", role: "button",style: "width: 20px;" } %>
							  <%= tag.div id: :notifications_count do %>
							    <%= render "notifications/count", count: current_user.unviewed_notifications_count %>
							  <% end %>
						  </div>
						<% end %>
          </li>
					
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><%= current_user.email %></a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
            	<%= link_to "Log out", destroy_user_session_path, :method => :delete ,class: 'dropdown-item'%>
            </div>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <!-- Page content-->
</div>	